application:
  appName: Sistema Gerenciador de Tarefas
  elasticsearch:
    url: localhost:9200

spring:
  application: gerenciadordetarefas
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/sgt
    username: sgt
    password: sgt
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
#    drop-first: true
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
feign:
  client:
    anexo:
      url: http://localhost:8081
